### ISSUE TITLE
just getting started 

### ISSUE THREAD

**Issue by munnecke** [SignalK/sk-plugin-python-demo#2]
I am just getting started in signalK and am interested in how to build plugins, so my first project is to do a python plugin to read an Adafruit BMO055 IMU sensor.  I'm wandering around a bit, learning SK and Github, so I'm happy to get any advice folks may have.  My project is https://github.com/munnecke/sk-plugin-BMO055

**Comment by tkurki** [comment]
👍 on your efforts! As this is not a specific question/issue I am going to close it. I think the best resource for you is our Slack community, also our GH Discussions https://github.com/SignalK/signalk/discussions. GH issues are great if you are having trouble with a specific piece of software or improvement ideas.
